site_name: Migration Tools
site_url: https://migration_tools.thoughtspot.com/
site_description: >-
  Migration Tools is a command line interface to help the __ThoughtSpot__ Professional
  Services team accelerate migration workflows.

repo_name: thoughtspot/migration_tools
repo_url: https://github.com/thoughtspot/migration_tools
edit_uri: tree/docs/docs/

copyright: Copyright &copy; 2022 ThoughtSpot Inc. All Rights Reserved

theme:
  name: material
  logo: assets/logo_white.png
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs

  font:
    text: Optimo-Plain
    code: BB Roller Mono

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: blue
      scheme: default
      # scheme: thoughtspot-light
      toggle:
        icon: material/lightbulb-outline
        name: switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: indigo
      scheme: slate
      # scheme: thoughtspot-dark
      toggle:
        icon: material/lightbulb
        name: switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - assets/overrides/.icons
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tilde
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thoughtspot/migration_tools
      name: find us on github

    - icon: fontawesome/solid/paper-plane
      link: mailto:nicholas.cooper@thoughtspot.com
      name: email the team

extra_css:
  - css/custom.css

nav:
  - Home: index.md
  - Tutorial:
    - "Getting Started": tutorial/intro.md
    - "Install & Upgrade": tutorial/install.md
    - "Setup a Config File": tutorial/config.md
    - "Running a Model validation": tutorial/validate.md
    - "Remapping a Connection File": tutorial/remapping.md
  - Tools:
    - migration-tools/overview.md
    - Create Config: migration-tools/create-config/readme.md
    - Convert DDLs: migration-tools/convert-ddls/readme.md
    - Validate Models: migration-tools/validate-models/readme.md
    - YAML Migrate: migration-tools/migrate-yaml/readme.md
    - Deltas: migration-tools/deltas/readme.md
    - Migrate Answers: migration-tools/answers/readme.md
    - Migrate Liveboards: migration-tools/liveboards/readme.md
    - Migrate Worksheets: migration-tools/worksheets/readme.md
    - Transfer Ownership: migration-tools/ownership/readme.md
    - Apply Tags: migration-tools/tags/readme.md
    - Share Permissions: migration-tools/share-permissions/readme.md
    - 🔐 Deploy: migration-tools/deploy/readme.md
    - 🔐 Compare Environments: migration-tools/compare/readme.md
  - Changelog:
    - v1.0.0: changelog/1.0.0.md
  - 🤓:
    - for-developers/contributing.md
    - for-developers/environment-setup.md

