[DATATYPE_MAPPINGS]
    [DATATYPE_MAPPINGS."INT"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."BIGINT"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."BIT"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."SMALLINT"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."TINYINT"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."VARCHAR(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."CHAR(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."DATETIMEOFFSET"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."NCHAR(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."NVARCHAR(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."UNIQUEIDENTIFIER"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."BINARY"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."VARBINARY"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."DATE"]
        TARGET_TYPE="DATE"
        YAML_TYPE="DATE"
        GROUP="DATES"
    [DATATYPE_MAPPINGS."DATETIME"]
        TARGET_TYPE="DATETIME"
        YAML_TYPE="DATE_TIME"
        GROUP="TIMESTAMPS"
    [DATATYPE_MAPPINGS."DATETIME2(X)"]
        TARGET_TYPE="DATETIME"
        YAML_TYPE="DATE_TIME"
        GROUP="TIMESTAMPS"
    [DATATYPE_MAPPINGS."DATETIME2"]
        TARGET_TYPE="DATETIME"
        YAML_TYPE="DATE_TIME"
        GROUP="TIMESTAMPS"
    [DATATYPE_MAPPINGS."SMALLDATETIME"]
        TARGET_TYPE="DATETIME"
        YAML_TYPE="DATE_TIME"
        GROUP="TIMESTAMPS"
    [DATATYPE_MAPPINGS."TIMESTAMP_NTZ(X)"]
        TARGET_TYPE="DATETIME"
        YAML_TYPE="DATE_TIME"
        GROUP="TIMESTAMPS"
    [DATATYPE_MAPPINGS."TIME(X)"]                 
        TARGET_TYPE="TIME"
        YAML_TYPE="TIME"
        GROUP="TIMES"
    [DATATYPE_MAPPINGS."TIME"]                 
        TARGET_TYPE="TIME"
        YAML_TYPE="TIME"
        GROUP="TIMES"
    [DATATYPE_MAPPINGS."DECIMAL(X,X)"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."DECIMAL(X)"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."NUMERIC(X,X)"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."NUMERIC(X)"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."NUMBER(X,X)"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."NUMBER(X)"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."FLOAT"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."FLOAT(X,X)"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."MONEY"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."REAL(X,X)"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."SMALLMONEY"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"