[DATATYPE_MAPPINGS]
    # List reverse mapping first
    [DATATYPE_MAPPINGS."INT"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT32"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."BIGINT"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."SMALLINT"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT32"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."TINYINT"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT32"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."DECIMAL(X)"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."DOUBLE"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."FLOAT"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."DECIMAL(X,X)"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."STRING"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."BINARY"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."BOOLEAN"]
        TARGET_TYPE="BOOL"
        YAML_TYPE="BOOL"
        GROUP="BOOLEANS"
    [DATATYPE_MAPPINGS."DATE"]
        TARGET_TYPE="DATE"
        YAML_TYPE="DATE"
        GROUP="DATES"
    [DATATYPE_MAPPINGS."TIMESTAMP"]
        TARGET_TYPE="DATETIME"
        YAML_TYPE="DATE_TIME"
        GROUP="TIMESTAMPS"
    # UNMAPPED:
    #[DATATYPE_MAPPINGS."INTERVAL(X)"]
    #[DATATYPE_MAPPINGS."VOID"]
    #ARRAY <elementType >
    #MAP < keyType,valueType >
    #STRUCT < [fieldName : fieldType [NOT NULL][COMMENT str][, …]] >


