# From: https://thoughtspot.atlassian.net/wiki/spaces/Embrace/pages/614039908/Datatype+Mappings
[DATATYPE_MAPPINGS]
    # List reverse mapping first
    [DATATYPE_MAPPINGS."INTEGER"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT32"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."INT"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT32"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."INT64"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."NUMERIC(X)"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."FLOAT"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."FLOAT64"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."NUMERIC(X,X)"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."BIGNUMERIC(X,X)"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."BOOLEAN"]
        TARGET_TYPE="BOOL"
        YAML_TYPE="BOOL"
        GROUP="BOOLEANS"
    [DATATYPE_MAPPINGS."BOOL"]
        TARGET_TYPE="BOOL"
        YAML_TYPE="BOOL"
        GROUP="BOOLEANS"
    [DATATYPE_MAPPINGS."STRING"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."BYTES"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."GEOGRAPHY"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."RECORD"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."DATE"]
        TARGET_TYPE="DATE"
        YAML_TYPE="DATE"
        GROUP="DATES"
    [DATATYPE_MAPPINGS."DATETIME"]
        TARGET_TYPE="DATE_TIME"
        YAML_TYPE="DATE"
        GROUP="DATES"
    [DATATYPE_MAPPINGS."TIMESTAMP"]
        TARGET_TYPE="DATETIME"
        YAML_TYPE="DATE_TIME"
        GROUP="TIMESTAMPS"
    [DATATYPE_MAPPINGS."TIME"]
        TARGET_TYPE="TIME"
        YAML_TYPE="TIME"
        GROUP="TIMES"
    #UNMAPPED:ARRAY,INTERVAL,JSON,STRUCT



