# From: https://thoughtspot.atlassian.net/wiki/spaces/Embrace/pages/614039908/Datatype+Mappings
[DATATYPE_MAPPINGS]
    # List reverse mapping first
    [DATATYPE_MAPPINGS."INTEGER"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT32"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."SMALLINT"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT32"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."INT2"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT32"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."INT"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT32"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."INT4"]
        TARGET_TYPE="INTEGER"
        YAML_TYPE="INT32"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."BIGINT"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."INT8"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."DECIMAL(X)"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."NUMERIC(X)"]
        TARGET_TYPE="BIGINT"
        YAML_TYPE="INT64"
        GROUP="INTEGERS"
    [DATATYPE_MAPPINGS."DOUBLE PRECISION"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."DECIMAL(X,X)"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."NUMERIC(X,X)"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."REAL"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="DOUBLE"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."FLOAT4"]
        TARGET_TYPE="DOUBLE"
        YAML_TYPE="FLOAT"
        GROUP="DOUBLE"
    [DATATYPE_MAPPINGS."BOOLEAN"]
        TARGET_TYPE="BOOL"
        YAML_TYPE="BOOL"
        GROUP="BOOLEANS"
    [DATATYPE_MAPPINGS."BOOL"]
        TARGET_TYPE="BOOL"
        YAML_TYPE="BOOL"
        GROUP="BOOLEANS"
    [DATATYPE_MAPPINGS."VARCHAR(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."CHAR(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."CHARACTER(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."NCHAR(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."BPCHAR(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."CHARACTER VARYING(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."NVARCHAR(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT" 
    [DATATYPE_MAPPINGS."TEXT(X)"]
        TARGET_TYPE="VARCHAR"
        YAML_TYPE="VARCHAR"
        GROUP="TEXT"
    [DATATYPE_MAPPINGS."DATE"]
        TARGET_TYPE="DATE"
        YAML_TYPE="DATE"
        GROUP="DATES"
    [DATATYPE_MAPPINGS."TIMESTAMP"]
        TARGET_TYPE="DATETIME"
        YAML_TYPE="DATE_TIME"
        GROUP="TIMESTAMPS"
    [DATATYPE_MAPPINGS."TIMESTAMPTZ"]
        TARGET_TYPE="DATETIME"
        YAML_TYPE="DATE_TIME"
        GROUP="TIMESTAMPS"
    [DATATYPE_MAPPINGS."TIME"]
        TARGET_TYPE="TIME"
        YAML_TYPE="TIME"
        GROUP="TIMES"
    [DATATYPE_MAPPINGS."TIMETZ"]
        TARGET_TYPE="TIME"
        YAML_TYPE="TIME"
        GROUP="TIMES"
    # Unmapped
    # "GEOMETRY","GEOGRAPHY","HLLSKETCH","SUPER","VARBYTE"